# action.yaml
name: "Python project version check"
description: "Compare Python package version from pyproject.toml and PyPI release and return true if local version is higher."
branding:
  icon: 'aperture'
  color: 'green'
inputs:
  pyproject-path:
    description: "location of pyproject file"
    required: true
    default: "./pyproject.toml"
  test_regex:
    description: "regex for testing whether destination is test.pypi.org or not"
    required: false
outputs:
  local_version_is_higher:
    description: "True if local version is higher than public version"
  local_version:
    description: "Local version of the package"
  public_version:
    description: "Public version of the package"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pyproject-path }}
